---
title: "Task4"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
load("../../module1/.RData")
cutpoint.Youden <- readRDS("../data/cutpoint.Youden.rds")
```

# --- Task 4 ---
### ROC stuff

```{r}
# Install if needed
#install.packages("pROC")

# Load package
library(pROC)

# Compute ROC curve
roc_obj <- roc(response = merged_all$metastasis, predictor = merged_all$psa)

# Plot ROC curve
plot(roc_obj, col = "#1f78b4", main = "ROC Curve for PSA vs. Metastasis", print.auc = TRUE)

# Get AUC
auc(roc_obj)

# Extract numeric cutoff from the result
youden_cutoff <- cutpoint.Youden$Youden$Global$optimal.cutoff[[1]]

# Confirm it's numeric
print(youden_cutoff)  # Should be 23

# Compute coordinates at that cutoff
coords <- coords(roc_obj, x = youden_cutoff, input = "threshold", ret = c("specificity", "sensitivity"))

# Add point to ROC plot
points(1 - coords["specificity"], coords["sensitivity"], col = "red", pch = 19)

text(1 - coords["specificity"], coords["sensitivity"], labels = paste0("Cutoff = ", youden_cutoff), pos = 3)



```






