---
title: "Task1"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
load("../../module1/.RData")
```

```{r}

# --- Task 1: Simple Logistic Regression ---
merged_all = readRDS('../../module1/data/merged_all.rds')
merged_all_new <- merged_all


# Build the logistic regression model
model_simple <- glm(metastasis ~ Urin_ret, data = merged_all, family = "binomial")

# Summarize the model
summary(model_simple)

# Interpret coefficients
exp(coef(model_simple))  # Exponentiate to get odds ratios

# Predict probabilities
merged_all$predicted_prob <- predict(model_simple, type = "response")

# Classify based on threshold 0.5
merged_all$predicted_class <- ifelse(merged_all$predicted_prob >= 0.5, 1, 0)

# Confusion matrix
table(Predicted = merged_all$predicted_class, Actual = merged_all$metastasis)

# Accuracy
accuracy <- mean(merged_all$predicted_class == merged_all$metastasis)

# Sensitivity and Specificity
TP <- sum(merged_all$predicted_class == 1 & merged_all$metastasis == 1)
TN <- sum(merged_all$predicted_class == 0 & merged_all$metastasis == 0)
FP <- sum(merged_all$predicted_class == 1 & merged_all$metastasis == 0)
FN <- sum(merged_all$predicted_class == 0 & merged_all$metastasis == 1)

sensitivity <- TP / (TP + FN)
specificity <- TN / (TN + FP)

# Print results
cat("Accuracy:", round(accuracy, 3), "\n")
cat("Sensitivity:", round(sensitivity, 3), "\n")
cat("Specificity:", round(specificity, 3), "\n")

library(pROC)

# ROC
roc_simple <- roc(merged_all$metastasis, merged_all$predicted_prob)

# Plot
plot(roc_simple, main = "ROC Curve - Urine Retention Model", col = "#1f78b4", print.auc = TRUE)




```